site_name: ALEX Embedded  Documentation
theme: readthedocs
nav:
  - Home: index.md
  - Requirements: requirements.md
  - Getting started: fastbuild.md
  - Workbench setup: workbench.md
  - Cross compliation: crosscomp.md
  - Eclipse w/ cross compliation: eclipse.md
  - Beagle Bone Black: bbb.md
  - Beagle Bone Kernel: kernel.md
  # - Everthing below this is in-development components. Move completed sections above.
  - IN-DEVELOPMENT: develop.md
  - CANbus: canbus.md
  - CANopen: canopen.md
  # - Real Time: relatime.md
  # - Misc: misc.md
  # - About: about.md
